### ISSUE TITLE
document how default ells are chosen for window calculation

### ISSUE THREAD

**Issue by pmcdonal** [cosmodesi/pypower#10]
This is almost a "just send Arnaud an email asking" (or try to look up in papers) thing, instead of an "issue," but probably others would benefit if it was written in the documentation. 
Off the top of my head, I don't know how the ells needed for the window are chosen. I.e., the meaning of "the list of projections is set to be able to compute window convolution of theory power spectrum multipoles of orders power_ref.ells".

**Comment by adematti** [comment]
I have added some explanations in 8e0f40f460a7370b92f0936782768df00298bc2c, see: https://github.com/cosmodesi/pypower/blob/f6f5e2636b26902cd87e23c72c2dd354d6e843d3/pypower/smooth_window.py#L521

**Comment by pmcdonal** [comment]
Thanks! I might write "maximum order yielded by the *sum* of any theory and output multipole" and/or refer to Eq. ~C.8 in my paper with Florian, if no better place. I know what you mean by "product"... the product in that equation... but to the user it may be puzzling when it is the sum of the ells. (I wonder if this limit *exact*, or a result of approximations in these equations?)

**Comment by adematti** [comment]
I changed this. What do you mean by "this limit is exact"? (Sometimes people truncate the window function multipoles after e.g. ell = 8, but I find no reason no to use all window function multipoles requested by theory).

**Comment by pmcdonal** [comment]
I had in my head something like "does l=10 really exactly not matter for the 4,4 window"... but I realize since you ask that this doesn't necessarily make much sense to ask, because the object carrying this l doesn't even appear in the more exact calculation.
