### ISSUE TITLE
MPI and mesh.readout

### ISSUE THREAD

**Issue by epaillas** [cosmodesi/pypower#19]
Hello - I was wondering if there is a way to take advantage of MPI parallelization when painting and sampling a density field on a mesh. My current attempt looks like

```
mesh  = CatalogMesh(data_positions=data_positions,
                    boxsize=boxsize, cellsize=cellsize,
                    resampler='cic', position_type='pos',
                    mpicomm=mpicomm, mpiroot=mpiroot)
```

where `data_positions` are gathered on rank 0. I'd like to smooth the field and sample it around random positions, so I'm doing 

```
data_mesh = mesh.to_mesh(field='data', compensate=True)
data_mesh = data_mesh.r2c().apply(Gaussian(r=smoothing_radius))
data_mesh = data_mesh.c2r()

norm = np.sum(data_mesh.value) / (nmesh[0]*nmesh[1]*nmesh[2])
density_mesh = data_mesh / norm - 1

if mpicomm.rank == mpiroot:
    sampling_positions = np.random.uniform(0, boxsize, (100_000, 3))
    density = density_mesh.readout(sampling_positions)
    np.save('density.npy', density)
```

I see a huge speed up when running the above on multiple processors with MPI, but the output density field is only correct when using a single process. What would be the proper way of sampling the field with multiple tasks?

Thanks a lot!

**Comment by adematti** [comment]
the only thing that you need to take care of is to distribute the particles in the domain of the grid each process keeps in memory. This can be done with:

```
sampling_positions = np.random.uniform(0, boxsize, (100_000, 3)) if mpicomm.rank == mpiroot else np.zeros((0, 3), dtype='f8')
resampler = 'cic'
layout = density_mesh.pm.decompose(positions, smoothing=resampler)
positions = layout.exchange(positions)   # exchange particles such that they are associated to the 
density = density_mesh.readout(positions, resampler=resampler)
density = layout.gather(values, mode='sum', out=None)  # redistribute particles as initially
if mpicomm.rank == mpiroot:  # only mpiroot has non-empty array of positions; if that was not the case, you need to mpi.gather(density, mpicomm=mpicomm, mpiroot=mpiroot) first
    np.save('density.npy', density)
    np.save('density.npy', density)
```

**Comment by epaillas** [comment]
Thanks for the prompt reply! I just tested what you proposed above, and now the shape of the PDF makes much more sense, although the normalization still seems to be off. I noticed that if I call `mpi.reduce` when calculating `norm`, the results are correct and agree with the single-process case:

`norm = mpicomm.allreduce(np.sum(data_mesh.value)) / (nmesh[0]*nmesh[1]*nmesh[2])`

Does this make sense to you? I Just wanna make sure I'm not compensating for some other mistake in my code.

**Comment by adematti** [comment]
yes, that's 100% correct, I forgot to specify that!

**Comment by epaillas** [comment]
Awesome, thanks a lot :) Everything seems to be working now. Sad thing is, my initial enthusiasm about the increase in speed has vanished now, as it seems the decrease in wallclock time doesn't compensate for the overhead from spawning multiple processes... 

I have now switched to the openMP multithreading implementation in pyrecon, which reduced the time my code spends in mesh calculations by more than 50%, so I'll probably stick to that for the moment. Thanks again for all the help!
