### ISSUE TITLE
don't interpolate in __call__ of smooth window if no input k... or something

### ISSUE THREAD

**Issue by pmcdonal** [cosmodesi/pypower#9]
I should have thought to look at the underlying "power" immediately, but, having followed examples or something, I was doing window1(proj=0) to access power, i.e., using here:
https://github.com/cosmodesi/pypower/blob/a6d91712229b61b00710ec1a533f89ffbfa9a121/pypower/smooth_window.py#L88
and spent a long time trying to figure out why the zero mode I was just trying to check value of was nan (until finally finding my way into this code)... turns out it was not in underlying power, but becoming nan through interpolation. 

Actually, even when you *are* interpolating here, it seems you should throw out the empty bins first. I.e., for the window calculation, just ignoring the empty bins and interpolating between filled ones seems like desired behavior... (maybe even interpolate back onto those ks when no k input)

**Comment by adematti** [comment]
It *should* be solved by 948546adc9fed1dc3ac510240c720657d7dcda0b.

**Comment by pmcdonal** [comment]
Looks fixed.
